# Generated by Django 5.2.6 on 2025-09-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Блоговую запись",
                "verbose_name_plural": "Блоговые записи",
            },
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Количество просмотров"
            ),
        ),
    ]
