# Generated by Django 5.2.6 on 2025-09-17 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: Телефон, Email, Адрес",
                        max_length=100,
                        verbose_name="Название пункта",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Например: +7 (999) 123-45-67",
                        max_length=200,
                        verbose_name="Значение",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительное описание",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Класс иконки (например: bi-telephone)",
                        max_length=50,
                        null=True,
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Чем меньше число, тем выше в списке",
                        verbose_name="Порядок отображения",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Показывать на сайте",
                        verbose_name="Активно",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
