# Generated by Django 5.2.6 on 2025-09-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="name",
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("phone", "Телефон"),
                    ("email", "Email"),
                    ("address", "Адрес"),
                    ("schedule", "Режим работы"),
                    ("other", "Другое"),
                ],
                default=1,
                help_text="Выберите тип контактной информации",
                max_length=20,
                verbose_name="Тип контакта",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Дополнительное описание (необязательно)",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Класс иконки Bootstrap Icons (например: bi-telephone)",
                max_length=50,
                null=True,
                verbose_name="Иконка",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="value",
            field=models.CharField(
                help_text="Например: +7 (999) 123-45-67 или info@example.com",
                max_length=200,
                verbose_name="Значение",
            ),
        ),
    ]
