# Generated by Django 5.2.6 on 2025-09-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_contact_name_contact_contact_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["-is_main_contact", "order", "contact_type"],
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.RemoveField(
            model_name="contact",
            name="created_at",
        ),
        migrations.AddField(
            model_name="contact",
            name="is_main_contact",
            field=models.BooleanField(
                default=False, verbose_name="Основной контакт для страницы"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="person_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Имя человека"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("phone", "Телефон"),
                    ("email", "Email"),
                    ("address", "Адрес"),
                    ("whatsapp", "WhatsApp"),
                    ("telegram", "Telegram"),
                    ("vk", "VK"),
                ],
                max_length=20,
                verbose_name="Тип контакта",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="icon",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Иконка"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активный"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="value",
            field=models.CharField(max_length=200, verbose_name="Значение"),
        ),
    ]
